### ISSUE TITLE
delete extracts

### ISSUE THREAD

**Issue by hlesaint** [openmindanesth/openmind#76]
Well, yes, difficult issue. I think it should not be possible. Maybe I just send you a list of extracts to delete? 

_"This is a new extract. It has been edited."_ could be deleted. 

Is there a possibility that the extracts affected in #75 are corrupt?

**Comment by tgetgood** [comment]
We could implement it as a "soft delete" where the extract is removed from the search index, so that it never comes up in results, but we keep it otherwise, so that if you have a link to it, you can still see it, and we can restore it if desired. We would have to choose whether to keep relations or not if we took this approach.

Alternately, I can give deletion privileges to a small group of admins, and leave it at that.

**Comment by hlesaint** [comment]
I think a soft delete is a good idea. Relations should be gone and restored with the extract. 

For me it would be perfectly fine to once in a while send you a request for deleting a particular extract. I believe this should be happening very rarely. 

The mentioned extract, for instance, was only a test, it cannot be edited and looks a bit weird when we start to invite contributors. This would be the only one I'd ask you to delete for now:

_"This is a new extract. It has been edited."_

**Comment by tgetgood** [comment]
I've set up the soft delete code. Just send me the url from the edit page of the extracts you think should be deleted in the future. 

It would be a good idea to open an issue for each set of deletions so that we have a record in case we decide we want to undelete something later on.
