### ISSUE TITLE
what's incomplete in your lab note?

### ISSUE THREAD

**Issue by hlesaint** [openmindanesth/openmind#91]
When trying to create incomplete lab notes, you cannot proceed but you may don't know why. It would be great to have a message next to the create button telling you at least one issue that you've forgot to do, or jump to the empty input field.

**Comment by tgetgood** [comment]
The missing field should have been highlighted in red already, so that should draw attention to the missing field.

I can add a message at the top of the page listing errors in the form as well, which will be visible without scrolling after you push save. This should have been done before, but was overlooked.

**Comment by hlesaint** [comment]
That's good and very helpful. Jumping to the filed which is highlighted in red is also a nice feature, which makes the process very convenient, but is not necessary.
